[package]
name = "file_encryption"
version = "0.1.0"
edition = "2021"

[dependencies]
aead = { version = "0.5.2", features = ["stream"] }
chacha20poly1305 = "0.10.1"
hex = "0.4.3"
rand = "0.9.0"
anyhow = "1.0.97"
argon2 = "0.5.3"
indicatif = "0.16"